export { default as Ecommerce } from './Ecommerce';
//export { default as Appointment } from './Appointment';
export { default as Kanban } from './Kanban';
//export { default as Orders } from './Orders';
export { default as Notification} from './Notification';
export { default as Doctor } from './Doctor';
export { default as Editor } from './Editor';
export { default as Customers } from './Customers';
//export { default as ColorPicker } from './ColorPicker';
export { default as Calendar } from './Calendar';
//export { default as Area } from './Charts/Area';
//export { default as Bar } from './Charts/Bar';
//export { default as ColorMapping } from './Charts/ColorMapping';
//export { default as Financial } from './Charts/Financial';
//export { default as Line } from './Charts/Line';
//export { default as Pie } from './Charts/Pie';
//export { default as Pyramid } from './Charts/Pyramid';
//export { default as Stacked } from './Charts/Stacked';
export { default as Appointment } from './Appointment';
export { default as Records} from './Records';
export { default as Prescription } from './Prescription';
export { default as Review} from './Review';
export { default as Emergency} from './Emergency';
export { default as Consultation} from './Consultation';
export { default as Billing}from './Billing';
export { default as QnA } from './QnA';
export { default as Remainder} from './Remainder';
export { default as Patient_Dashboard} from './Patient_Dashboard';

